---
services:
  coredns:
    build:
      context: .
      platforms:
        - "linux/arm64"
        - "linux/amd64"
    image: ghcr.io/carme-264pp/coredns-docker:latest
    restart: always
    ports:
      - 53:53/udp
      - 53:53/tcp
    volumes:
      - ./config:/etc/coredns:ro
    networks:
      - coredns_net
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

networks:
  coredns_net:
